apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    storage: prometheus
  name: promethues-iscsi-pv
spec:
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  iscsi:
     targetPortal: ${ISCSI_TARGET_PORTAL}
     iqn: ${ISCSI_IQN}
     lun: ${ISCSI_LUN_ID}
     fsType: 'ext4'
     readOnly: false


